codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    status:
      project:
        default:
          threshold: 1
        server:
          threshold: 0.5
          paths:
            - backend/*
            - tests/server_tests/*
            - tests/integration_tests/*
        website:
          threshold: 0.5
          paths:
            - webapp/*
    patch: off
    changes: no

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "header, diff"
  behavior: default
  require_changes: no

ingore:
  - "helpers/*"
  - "data/*"
  - "redis/*"