version: "3"
services:
  postgres:
    image: postgres:10-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - "calculated.gg.postgres:/var/lib/postgresql/data"

  redis:
    image: redis:4-alpine
    restart: always
    volumes:
      - "calculated.gg.redis:/data"
  
  nginx:
    build: 
      dockerfile: Dockerfile
      context: ./nginx
    restart: always
    ports:
      - 5000:80
    depends_on:
      - flask
      - webapp

  flask:
    build: 
      dockerfile: Dockerfile.flask
      context: ./
    ports:
      - 8000:8000
    depends_on:
      - postgres
      - redis
    volumes:
      - calculated.gg.replays:/app/data

  celery:
    build:
      dockerfile: Dockerfile.celery
      context: ./
    command: celery -A backend.tasks.celery_tasks.celery worker --loglevel=INFO
    depends_on:
      - redis
      - flask
    volumes:
      - calculated.gg.replays:/app/data

  webapp:
    build:
      context: ./webapp
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000

volumes:
  calculated.gg.postgres:
  calculated.gg.redis:
  calculated.gg.replays:
