FROM python:3.6-alpine

WORKDIR /app

ENV DOCKERIZE_VERSION v0.6.1

ADD requirements.txt .

RUN apk --no-cache --update-cache add \
    build-base \
    freetype-dev \
    gcc \
    libpng-dev \
    musl-dev \
    postgresql-dev
RUN pip install --no-cache-dir -r requirements.txt

RUN wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-alpine-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
    && tar -C /usr/local/bin -xzvf dockerize-alpine-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
    && rm dockerize-alpine-linux-amd64-$DOCKERIZE_VERSION.tar.gz
